name: Deploy to EC2

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          #This(-p) ensures even if .ssh is present it will not fail
          #chmod 600 is essential because of pvt key only the main user must have complete access and 0 access to others its basically rwx(binary format)
          # ssh-keyscan is used to add the EC2 instance to the known_hosts file it is necessary bcoz first time when connecting it will ask are you sure to connect where we have to type yes, but thats not possible with Github actions so directly preload the host to known hosts file -H hashs the host key for better privacy
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh    
          echo "${{ secrets.EC2_SSH_PVT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo $USER
          ls -la
          cd ~/.ssh
          ls -la

      - name: Deploy to GCP using SSH and using PM2
        run: |
          echo $USER
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo $USER && ls -la"
